name: Build and Publish Docker Images

on:
  push:
    branches:
      - review-3

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репо
      - name: Checkout repository
        uses: actions/checkout@v4

      # Настраиваем Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Логин в GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Сборка и push FRONTEND
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/film-frontend:latest

      # Сборка и push BACKEND
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/film-backend:latest

      # Сборка и push NGINX
      - name: Build and push nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/film-nginx:latest
